version: '3.4'

services:
  db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: wsc-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/postgres:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
  app:
    container_name: wsc-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      WAIT_HOSTS: db:5432
